In [1]:
from PIL import Image, ImageFilter, ImageDraw, ImageFont
from PIL.ImageFilter import CONTOUR, EDGE_ENHANCE, SMOOTH
import numpy as np

In [2]:
img= Image.open('1.jpg')
img.show()

In [ ]:
img_rotate = img.rotate(45)
img_rotate.save('2.jpg')
img_rotate.show()
img

In [6]:
r, g, b = img.split()
img.show()
r.show()
g.show()
b.show()

new_img = Image.merge("RGB", (b, r, g))
new_img.show()
new_img.save('15.png')

In [36]:
img_blur = img.filter(ImageFilter.BLUR)
img_blur.show()
img_blur.save('3.png')

In [3]:
gaussian_blur_img = img.filter(ImageFilter.GaussianBlur(radius= 5))
gaussian_blur_img.show()
gaussian_blur_img.save("4.png")

In [4]:
con_img = img.filter(CONTOUR)
con_img.show()
con_img.save("5.png")

In [5]:
edge_img = img.filter(EDGE_ENHANCE)
edge_img.show()
edge_img.save("6.png")

In [6]:
smooth_img = img.filter(SMOOTH)
smooth_img.show()
smooth_img.save("7.png")

In [7]:
flipped_img = img.transpose(Image.FLIP_LEFT_RIGHT)
flipped_img.show()
flipped_img.save("8.png")

In [26]:
flipped_img2 = img.transpose(Image.FLIP_TOP_BOTTOM)
flipped_img2.show()
flipped_img2.save("9.png")

In [10]:
imgBG= Image.new('RGB', (500, 300), (200, 200, 200))
draw= ImageDraw.Draw(imgBG)

In [11]:
draw.rectangle((50, 50, 200, 150), fill=(255, 255, 255), outline= (0, 0, 0))
draw.polygon(([(100, 50), (50, 200), (150, 200)]), fill=(0, 255, 0), outline=(0, 0, 255))
imgBG.show()
imgBG.save("10.png")

In [19]:
img2= Image.open('1.jpg')

waterMark= ImageDraw.Draw(img2)

#font= ImageFont.truetype('arial.tff',36)

font= ImageFont.load_default()
width, height= img2.size
x= width/2
y= height/2

text= 'Duck Duck Duck Duck'
waterMark.text((x, y), text, fill=(255, 255, 00), font= font)

img2.show()
img2.save('11.png')

In [21]:
grayscale_img= img.convert('RGB')

matrix= np.array(grayscale_img)
print(matrix)

[[[179 217 168]
  [179 217 168]
  [179 217 168]
  ...
  [179 217 168]
  [179 217 168]
  [179 217 168]]

 [[179 217 168]
  [179 217 168]
  [179 217 168]
  ...
  [179 217 168]
  [179 217 168]
  [179 217 168]]

 [[179 217 168]
  [179 217 168]
  [179 217 168]
  ...
  [179 217 168]
  [179 217 168]
  [179 217 168]]

 ...

 [[179 217 168]
  [179 217 168]
  [179 217 168]
  ...
  [179 217 168]
  [179 217 168]
  [179 217 168]]

 [[179 217 168]
  [179 217 168]
  [179 217 168]
  ...
  [179 217 168]
  [179 217 168]
  [179 217 168]]

 [[179 217 168]
  [179 217 168]
  [179 217 168]
  ...
  [179 217 168]
  [179 217 168]
  [179 217 168]]]


In [22]:
brighter= np.clip(matrix+ 50, 0, 255)
darker= np.clip(matrix- 50, 0, 255)

In [23]:
brightimg= Image.fromarray(brighter.astype('uint8'))
brightimg.show()
brightimg.save('13.png')


In [24]:
darkimg= Image.fromarray(darker.astype('uint8'))
darkimg.show()
darkimg.save('12.png')

In [ ]:
randomarray= np.random.randint(0, 256, (256, 256, 3), dtype= np.uint8)

grayimg= Image.fromarray(randomarray, mode= 'RGB')
grayimg.show()


In [27]:
def salt_pepper_noise(img, saltProb=0.02, pepperProb=0.02):

    imgArray = np.asarray(img)
    noisyArray = imgArray.copy()
    totalPix = imgArray.shape[0] * imgArray.shape[1]

    numSalt = int(saltProb * totalPix) 
    coords_salt = [np.random.randint(0, i - 1, numSalt) for i in imgArray.shape[:2]]  
    
    noisyArray[coords_salt[0], coords_salt[1]] = 255  

    numPepper = int(pepperProb * totalPix)  
    coords_pepper = [np.random.randint(0, i - 1, numPepper) for i in imgArray.shape[:2]]  

    noisyArray[coords_pepper[0], coords_pepper[1]] = 0  
    noisyImg = Image.fromarray(noisyArray.astype(np.uint8))  

    return noisyImg


img = Image.open('1.jpg').convert('L')


img2 = salt_pepper_noise(img)
img2.show()
img2.save('14.jpg')

In [12]:
noise_img= Image.open('14.jpg')
noise_img.show()

matrix= np.array(noise_img).astype('int')
print(matrix)

for i in range(1, matrix.shape[0]-1):
    for j in range(1, matrix.shape[1]-1):
        window = [
            matrix[i-1][j-1], matrix[i-1][j], matrix[i-1][j+1],
            matrix[i][j-1],   matrix[i][j],   matrix[i][j+1],
            matrix[i+1][j-1], matrix[i+1][j], matrix[i+1][j+1]
        ]
        window.sort()
        matrix[i]= window[4]
matrix= matrix.astype('uint8')

matrix= Image.fromarray(matrix)
matrix.show()

[[200 192 206 ... 207 200 200]
 [210 207 206 ... 192 200 200]
 [196 189   0 ... 208 200 200]
 ...
 [216 206 199 ... 216 200 200]
 [225 210 198 ... 225 200 200]
 [215 204 196 ... 215 200 200]]
